zuul:
  routes:
    backend-power:
      path: /power/**
      serviceId: backend-power

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

server:
  port: 8079

spring:
  application:
    name: zuul-service

